import { createFileRoute } from "@tanstack/react-router";

import { COMPANY } from "@/lib/legal";
import { LegalPage, LegalSection } from "@/components/legal-page";

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [
      { title: "Terms of Use — Africa Opportunity Hub" },
      {
        name: "description",
        content:
          "The rules for using Nuru AI and the Africa Opportunity Map: acceptable use, AI accuracy limits, contributions, and liability.",
      },
      { property: "og:title", content: "Terms of Use — Africa Opportunity Hub" },
      {
        property: "og:description",
        content: "Acceptable use, AI accuracy limits and contribution rules.",
      },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary" },
    ],
  }),
  component: TermsPage,
});

function TermsPage() {
  return (
    <LegalPage
      title="Terms of Use"
      intro={`The agreement between you and ${COMPANY.name} when you use ${COMPANY.product} and the Africa Opportunity Map.`}
    >
      <LegalSection title="Accepting these terms">
        <p>
          By using the platform you agree to these terms. If you do not agree, please do not use it.
          {" "}
          {COMPANY.status} These terms will be updated as the company formalises.
        </p>
      </LegalSection>

      <LegalSection title="What the service is">
        <p>
          We provide an AI assistant, a public map of African problems and opportunities, a research
          library and a business hub. The service is offered as-is, free of charge at this stage,
          and may change or be interrupted while we build.
        </p>
      </LegalSection>

      <LegalSection title="AI output is not verified fact">
        <p>
          Answers, analyses and summaries are generated by AI. They may be incomplete, out of date
          or wrong. Where we show web sources, those pages belong to third parties and we do not
          endorse or guarantee them. Nothing here is legal, financial, medical, agricultural or
          investment advice. Verify locally before making decisions, and treat every number as a
          hypothesis to check.
        </p>
      </LegalSection>

      <LegalSection title="Acceptable use">
        <ul>
          <li>Do not submit unlawful, hateful, defamatory or deliberately false content.</li>
          <li>Do not upload other people&apos;s private or personal information.</li>
          <li>Do not attempt to break, overload, scrape abusively or bypass rate limits.</li>
          <li>Do not use the platform to build weapons, run fraud or harm people.</li>
        </ul>
        <p>We may remove content or restrict access where these rules are broken.</p>
      </LegalSection>

      <LegalSection title="Your contributions">
        <p>
          You keep ownership of what you submit. By submitting a problem, research entry or other
          contribution for publication, you grant us a non-exclusive, worldwide licence to publish,
          display and distribute it as part of the public Opportunity Map, including through our
          public read-only agent endpoint. You confirm you have the right to share it.
        </p>
      </LegalSection>

      <LegalSection title="Our content">
        <p>
          The {COMPANY.product} name, branding, design and software remain ours. Public map entries
          may be read and cited with attribution to {COMPANY.name}.
        </p>
      </LegalSection>

      <LegalSection title="Availability and liability">
        <p>
          We do not promise uninterrupted service. To the maximum extent permitted by applicable
          law, we are not liable for indirect or consequential loss, lost profits, or decisions made
          in reliance on AI output or third-party sources.
        </p>
      </LegalSection>

      <LegalSection title="Governing law">
        <p>
          Until the company is formally incorporated, disputes will be handled in good faith through
          direct discussion. Our planned jurisdiction is {COMPANY.plannedJurisdiction}; we will
          publish a governing-law clause once incorporation is complete.
        </p>
      </LegalSection>

      <LegalSection title="Contact">
        <p>
          Questions about these terms: <a href={`mailto:${COMPANY.legalEmail}`}>{COMPANY.legalEmail}</a>.
          Help using the platform: <a href={`mailto:${COMPANY.supportEmail}`}>{COMPANY.supportEmail}</a>.
        </p>
      </LegalSection>
    </LegalPage>
  );
}
