/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BuildersRouteImport } from './routes/builders'
import { Route as EcosystemRouteImport } from './routes/ecosystem'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as ProblemMapRouteImport } from './routes/problem-map'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as OpportunitiesIndexRouteImport } from './routes/opportunities.index'
import { Route as OpportunitiesSlugRouteImport } from './routes/opportunities.$slug'
import { Route as ProblemsIndexRouteImport } from './routes/problems.index'
import { Route as ProblemsSlugRouteImport } from './routes/problems.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildersRoute = BuildersRouteImport.update({
  id: '/builders',
  path: '/builders',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemRoute = EcosystemRouteImport.update({
  id: '/ecosystem',
  path: '/ecosystem',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemMapRoute = ProblemMapRouteImport.update({
  id: '/problem-map',
  path: '/problem-map',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesIndexRoute = OpportunitiesIndexRouteImport.update({
  id: '/opportunities/',
  path: '/opportunities/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesSlugRoute = OpportunitiesSlugRouteImport.update({
  id: '/opportunities/$slug',
  path: '/opportunities/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsIndexRoute = ProblemsIndexRouteImport.update({
  id: '/problems/',
  path: '/problems/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsSlugRoute = ProblemsSlugRouteImport.update({
  id: '/problems/$slug',
  path: '/problems/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/builders': typeof BuildersRoute
  '/ecosystem': typeof EcosystemRoute
  '/insights': typeof InsightsRoute
  '/problem-map': typeof ProblemMapRoute
  '/projects': typeof ProjectsRoute
  '/research': typeof ResearchRoute
  '/solutions': typeof SolutionsRoute
  '/submit': typeof SubmitRoute
  '/opportunities/$slug': typeof OpportunitiesSlugRoute
  '/problems/$slug': typeof ProblemsSlugRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
  '/problems/': typeof ProblemsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/builders': typeof BuildersRoute
  '/ecosystem': typeof EcosystemRoute
  '/insights': typeof InsightsRoute
  '/problem-map': typeof ProblemMapRoute
  '/projects': typeof ProjectsRoute
  '/research': typeof ResearchRoute
  '/solutions': typeof SolutionsRoute
  '/submit': typeof SubmitRoute
  '/opportunities/$slug': typeof OpportunitiesSlugRoute
  '/problems/$slug': typeof ProblemsSlugRoute
  '/opportunities': typeof OpportunitiesIndexRoute
  '/problems': typeof ProblemsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/builders': typeof BuildersRoute
  '/ecosystem': typeof EcosystemRoute
  '/insights': typeof InsightsRoute
  '/problem-map': typeof ProblemMapRoute
  '/projects': typeof ProjectsRoute
  '/research': typeof ResearchRoute
  '/solutions': typeof SolutionsRoute
  '/submit': typeof SubmitRoute
  '/opportunities/$slug': typeof OpportunitiesSlugRoute
  '/problems/$slug': typeof ProblemsSlugRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
  '/problems/': typeof ProblemsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/builders'
    | '/ecosystem'
    | '/insights'
    | '/problem-map'
    | '/projects'
    | '/research'
    | '/solutions'
    | '/submit'
    | '/opportunities/$slug'
    | '/problems/$slug'
    | '/opportunities/'
    | '/problems/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/builders'
    | '/ecosystem'
    | '/insights'
    | '/problem-map'
    | '/projects'
    | '/research'
    | '/solutions'
    | '/submit'
    | '/opportunities/$slug'
    | '/problems/$slug'
    | '/opportunities'
    | '/problems'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/builders'
    | '/ecosystem'
    | '/insights'
    | '/problem-map'
    | '/projects'
    | '/research'
    | '/solutions'
    | '/submit'
    | '/opportunities/$slug'
    | '/problems/$slug'
    | '/opportunities/'
    | '/problems/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BuildersRoute: typeof BuildersRoute
  EcosystemRoute: typeof EcosystemRoute
  InsightsRoute: typeof InsightsRoute
  ProblemMapRoute: typeof ProblemMapRoute
  ProjectsRoute: typeof ProjectsRoute
  ResearchRoute: typeof ResearchRoute
  SolutionsRoute: typeof SolutionsRoute
  SubmitRoute: typeof SubmitRoute
  OpportunitiesSlugRoute: typeof OpportunitiesSlugRoute
  ProblemsSlugRoute: typeof ProblemsSlugRoute
  OpportunitiesIndexRoute: typeof OpportunitiesIndexRoute
  ProblemsIndexRoute: typeof ProblemsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builders': {
      id: '/builders'
      path: '/builders'
      fullPath: '/builders'
      preLoaderRoute: typeof BuildersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem': {
      id: '/ecosystem'
      path: '/ecosystem'
      fullPath: '/ecosystem'
      preLoaderRoute: typeof EcosystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problem-map': {
      id: '/problem-map'
      path: '/problem-map'
      fullPath: '/problem-map'
      preLoaderRoute: typeof ProblemMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/': {
      id: '/opportunities/'
      path: '/opportunities'
      fullPath: '/opportunities/'
      preLoaderRoute: typeof OpportunitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/$slug': {
      id: '/opportunities/$slug'
      path: '/opportunities/$slug'
      fullPath: '/opportunities/$slug'
      preLoaderRoute: typeof OpportunitiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems/': {
      id: '/problems/'
      path: '/problems'
      fullPath: '/problems/'
      preLoaderRoute: typeof ProblemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems/$slug': {
      id: '/problems/$slug'
      path: '/problems/$slug'
      fullPath: '/problems/$slug'
      preLoaderRoute: typeof ProblemsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BuildersRoute: BuildersRoute,
  EcosystemRoute: EcosystemRoute,
  InsightsRoute: InsightsRoute,
  ProblemMapRoute: ProblemMapRoute,
  ProjectsRoute: ProjectsRoute,
  ResearchRoute: ResearchRoute,
  SolutionsRoute: SolutionsRoute,
  SubmitRoute: SubmitRoute,
  OpportunitiesSlugRoute: OpportunitiesSlugRoute,
  ProblemsSlugRoute: ProblemsSlugRoute,
  OpportunitiesIndexRoute: OpportunitiesIndexRoute,
  ProblemsIndexRoute: ProblemsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
